language: android
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools
    - build-tools-25.0.3
    - android-25
    # Additional components
    - extra-google-m2repository
script:
  - ./gradlew assembleRelease